apiVersion: v1
kind: Pod
metadata:
  name: employee-record-app
  namespace: santhosh5858-dev
spec:
  containers:
    - name: employee-record-container
      image: docker.io/jilla5858/employeeappimage:latest
      ports:
        - containerPort: 8080
    
